### ISSUE TITLE
Uploading the same content twice no longer errors

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_file#958]
[This feature](https://github.com/pulp/pulp_file/issues/774) allows a user to upload a file content unit that someone else already uploaded without getting an error. But it also includes a backwards incompatible change: if a user uploads the same content unit twice, they no longer get an error. If this behavior is expected, then based on my understanding of semver, the major version of the release (1.12.0) should have been bumped as features with backwards incompatible changes necessitate increasing the major version.

Relevant discussion on discourse: https://discourse.pulpproject.org/t/unable-to-upload-packages-to-rpm-repo-if-allready-stored-in-pulp/841/6?u=davidd

**Comment by daviddavis** [comment]
I'm not too concerned about the fact that the major release wasn't bumped. But I'd maybe suggest that:

* A "removal" entry gets added to the changelog (assuming that removals include breaking changes?)
* Or the changelog entry includes more information about the potential implications for users

Currently our codebase expects an error to get raised if a content unit is uploaded twice.

**Comment by lubosmj** [comment]
This is an expected behaviour. We are really sorry that we did not provide sufficient information about the potential implications for you, causing confusion and frustration.

This oversight was a mistake on our part, and we take full responsibility for it. We will try to ensure that similar incidents are avoided in the future.
